#!/bin/bash

###############################################################################
#
#  ███╗   ███╗███████╗███╗   ███╗███████╗██╗      █████╗ ██╗   ██╗███╗   ██╗ ██████╗██╗  ██╗███████╗██████╗
#  ████╗ ████║██╔════╝████╗ ████║██╔════╝██║     ██╔══██╗██║   ██║████╗  ██║██╔════╝██║  ██║██╔════╝██╔══██╗
#  ██╔████╔██║█████╗  ██╔████╔██║█████╗  ██║     ███████║██║   ██║██╔██╗ ██║██║     ███████║█████╗  ██████╔╝
#  ██║╚██╔╝██║██╔══╝  ██║╚██╔╝██║██╔══╝  ██║     ██╔══██║██║   ██║██║╚██╗██║██║     ██╔══██║██╔══╝  ██╔══██╗
#  ██║ ╚═╝ ██║███████╗██║ ╚═╝ ██║███████╗███████╗██║  ██║╚██████╔╝██║ ╚████║╚██████╗██║  ██║███████╗██║  ██║
#  ╚═╝     ╚═╝╚══════╝╚═╝     ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
#
#  🚀 Fair Meme Token Launchpad for Base Testnet
#  📊 Live Deployment Script
#
###############################################################################

# Load environment variables
source .env

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║              DEPLOYING BASE MEME LAUNCHER                     ║"
echo "╠════════════════════════════════════════════════════════════════╣"
echo ""

echo "🔧 Configuration:"
echo "   RPC URL: $BASE_SEPOLIA_RPC_URL"
echo "   Account: defaultKey"
echo "   Network: Base Sepolia Testnet (Chain ID: 84532)"
echo ""

# Deploy BaseMemeLauncher to Base Sepolia testnet
forge script script/DeployMemeLauncher.s.sol \
  --rpc-url $BASE_SEPOLIA_RPC_URL \
  --account defaultKey \
  --broadcast \
  --verify \
  --etherscan-api-key $BASESCAN_API_KEY

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                    DEPLOYMENT COMPLETE                        ║"
echo "╠════════════════════════════════════════════════════════════════╣"
echo ""

echo "📋 Next Steps:"
echo "1. Copy the deployed contract address"
echo "2. Update frontend with new contract address"
echo "3. Test the launchpad on Base Sepolia"
echo "4. Promote on X for viral launches!"
echo ""

echo "🎯 Leaderboard Goals:"
echo "   • 50+ launches before midnight"
echo "   • 1% fee per launch = treasury rewards"
echo "   • Top creators win ETH prizes"
echo ""

echo "╚════════════════════════════════════════════════════════════════╝"

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         MEMÉ LAUNCHER - QUICK START COMMANDS                  ║"
echo "╠════════════════════════════════════════════════════════════════╣"
echo ""

echo "📦 STEP 1: SETUP ENVIRONMENT"
echo "─────────────────────────────────────────────────────────────────"
echo "# Install Foundry (if not installed)"
echo "curl -L https://foundry.paradigm.xyz | bash"
echo ""
echo "# Install dependencies"
echo "cd solidityContract"
echo "forge install"
echo ""

echo "🔨 STEP 2: COMPILE CONTRACTS"
echo "─────────────────────────────────────────────────────────────────"
echo "forge build"
echo ""

echo "✅ STEP 3: RUN TESTS (40+ test cases)"
echo "─────────────────────────────────────────────────────────────────"
echo "# Run all tests"
echo "forge test"
echo ""
echo "# Run with verbose output"
echo "forge test -v"
echo ""
echo "# Run specific test category"
echo "forge test -k test_Launch    # Only launch tests"
echo "forge test -k test_Admin     # Only admin tests"
echo "forge test -k test_MemeToken # Only token tests"
echo ""

echo "🌐 STEP 4: SET ENVIRONMENT VARIABLES"
echo "─────────────────────────────────────────────────────────────────"
echo "export PRIVATE_KEY=\"your_private_key_hex_without_0x_prefix\""
echo "export BASE_TESTNET_RPC=\"https://84532.rpc.thirdweb.com/\""
echo ""

echo "🚀 STEP 5: DEPLOY TO BASE TESTNET (ChainID: 84532)"
echo "─────────────────────────────────────────────────────────────────"
echo "forge script script/DeployMemeLauncher.s.sol \\"
echo "  --rpc-url \$BASE_TESTNET_RPC \\"
echo "  --private-key \$PRIVATE_KEY \\"
echo "  --broadcast"
echo ""
echo "⚠️  Alternative: If PRIVATE_KEY env var fails:"
echo "forge script script/DeployMemeLauncher.s.sol \\"
echo "  --rpc-url \$BASE_TESTNET_RPC \\"
echo "  --broadcast --interactive"
echo ""

echo "🎯 STEP 6: VERIFY DEPLOYMENT"
echo "─────────────────────────────────────────────────────────────────"
echo "export LAUNCHER_ADDRESS=\"0x...\" # From deployment output"
echo ""
echo "# Check minimum launch ETH"
echo "cast call \$LAUNCHER_ADDRESS \"minLaunchETH()\" \\"
echo "  --rpc-url \$BASE_TESTNET_RPC"
echo ""
echo "# Check treasury address"
echo "cast call \$LAUNCHER_ADDRESS \"treasury()\" \\"
echo "  --rpc-url \$BASE_TESTNET_RPC"
echo ""
echo "# Check total launches"
echo "cast call \$LAUNCHER_ADDRESS \"totalLaunches()\" \\"
echo "  --rpc-url \$BASE_TESTNET_RPC"
echo ""

echo "🎨 STEP 7: LAUNCH YOUR FIRST MEME TOKEN"
echo "─────────────────────────────────────────────────────────────────"
echo "# Get testnet ETH from faucet first:"
echo "# https://coinbase.com/faucets/base-ethereum-sepolia-faucet"
echo ""
echo "# Option A: Using cast (command-line)"
echo "cast send \$LAUNCHER_ADDRESS \\"
echo "  'launchMeme(string,string,uint256,uint256)' \\"
echo "  'Doge Meme' 'DOGE' '1000000000000000000000000000' 20 \\"
echo "  --value 0.5ether \\"
echo "  --rpc-url \$BASE_TESTNET_RPC \\"
echo "  --private-key \$PRIVATE_KEY"
echo ""
echo "# Option B: Using Foundry script (advanced)"
echo "# Create custom launch script in script/"
echo ""
echo "# Option C: Using Web3 interaction library"
echo "# JavaScript, Python, or your preferred Web3 library"
echo ""

echo "📊 STEP 8: CHECK YOUR LAUNCH"
echo "─────────────────────────────────────────────────────────────────"
echo "# Get all launched tokens"
echo "cast call \$LAUNCHER_ADDRESS \\"
echo "  'getAllLaunchedTokens()' \\"
echo "  --rpc-url \$BASE_TESTNET_RPC"
echo ""
echo "# Get your launch count"
echo "cast call \$LAUNCHER_ADDRESS \\"
echo "  'getCreatorLaunchCount(address)' 0xYourAddress \\"
echo "  --rpc-url \$BASE_TESTNET_RPC"
echo ""
echo "# Check total fees collected (treasury rewards)"
echo "cast call \$LAUNCHER_ADDRESS \\"
echo "  'totalFeesCollected()' \\"
echo "  --rpc-url \$BASE_TESTNET_RPC"
echo ""

echo "💱 STEP 9: TRADE ON UNISWAP V3"
echo "─────────────────────────────────────────────────────────────────"
echo "1. Visit: https://app.uniswap.org/"
echo "2. Click 'Connect' and select MetaMask"
echo "3. Switch network to 'Base Sepolia'"
echo "4. Paste your token address in the search"
echo "5. Swap WETH ↔ Your Meme Token"
echo "6. Celebrate! 🎉"
echo ""

echo "📈 STEP 10: CLIMB THE LEADERBOARD"
echo "─────────────────────────────────────────────────────────────────"
echo "Tracked metrics:"
echo "  • Total launches by creator"
echo "  • Total ETH committed to liquidity"
echo "  • Total fees collected (1% per launch)"
echo "  • Trading volume on Uniswap V3"
echo ""
echo "Formula: Score = (Total ETH) * 0.7 + (Total Fees) * 100"
echo ""
echo "Win prizes:"
echo "  🥇 Top 5: 50% of treasury pool"
echo "  🥈 Top 15: 30% of treasury pool"
echo "  🏅 Community choice: 15% bonus"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                    USEFUL COMMANDS                            ║"
echo "╠════════════════════════════════════════════════════════════════╣"
echo ""

echo "Development:"
echo "  forge build              - Compile contracts"
echo "  forge test               - Run all tests"
echo "  forge test -v            - Verbose test output"
echo "  forge test -vv           - Full trace output"
echo "  forge fmt                - Format code"
echo "  forge gas-report         - Show gas costs"
echo ""

echo "Deployment:"
echo "  forge script ...         - Run deployment"
echo "  cast send                - Send transaction"
echo "  cast call                - Call view function"
echo ""

echo "Verification:"
echo "  cast balance <addr>      - Check ETH balance"
echo "  cast call <addr> <func>  - Query contract state"
echo "  cast code <addr>         - View deployed bytecode"
echo ""

echo "Block Explorer:"
echo "  https://sepolia.basescan.org/  (Base Sepolia)"
echo ""

echo "Faucet:"
echo "  https://coinbase.com/faucets/base-ethereum-sepolia-faucet"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║               FILE STRUCTURE OVERVIEW                         ║"
echo "╠════════════════════════════════════════════════════════════════╣"
echo ""
echo "solidityContract/"
echo "├── src/"
echo "│   ├── MemeToken.sol              # Simple ERC-20 token"
echo "│   └── BaseMemeLauncher.sol        # Main launchpad contract"
echo "│"
echo "├── test/"
echo "│   └── Launcher.t.sol              # 40+ test cases"
echo "│"
echo "├── script/"
echo "│   └── DeployMemeLauncher.s.sol    # Deployment script"
echo "│"
echo "├── lib/"
echo "│   ├── forge-std/                  # Foundry testing"
echo "│   └── openzeppelin-contracts/     # Security libraries"
echo "│"
echo "├── README.md                       # Complete documentation"
echo "├── QUICKSTART.md                   # Visual guide"
echo "├── ARCHITECTURE.md                 # Technical deep-dive"
echo "├── DEPLOY.sh                       # This file"
echo "└── foundry.toml                    # Build configuration"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                  KEY CONTRACT FEATURES                        ║"
echo "╠════════════════════════════════════════════════════════════════╣"
echo ""
echo "✅ Fair Launch Mechanism"
echo "   • Creator gets 80% of supply"
echo "   • Instant Uniswap V3 liquidity (0.3% fee tier)"
echo "   • 1% launch fee to treasury"
echo ""
echo "✅ Security"
echo "   • ReentrancyGuard protection"
echo "   • OpenZeppelin standards"
echo "   • Admin controls (owner only)"
echo "   • Emergency withdrawal mechanisms"
echo ""
echo "✅ Transparency"
echo "   • All events emitted"
echo "   • View functions for statistics"
echo "   • Leaderboard-ready metrics"
echo ""
echo "✅ Simplicity"
echo "   • Minimal code (no bloat)"
echo "   • Clear function purposes"
echo "   • Easy to audit and verify"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                  TROUBLESHOOTING                              ║"
echo "╠════════════════════════════════════════════════════════════════╣"
echo ""
echo "❌ \"Insufficient balance\" on deployment:"
echo "   → Get testnet ETH from faucet first"
echo ""
echo "❌ \"Allowance insufficient\" when launching:"
echo "   → Creator must approve tokens to launcher first"
echo "   → cast send <TOKEN> 'approve(address,uint256)' <LAUNCHER> <AMOUNT>"
echo ""
echo "❌ \"Pool already exists\" error:"
echo "   → Normal if launching to same token address twice"
echo "   → Uniswap V3 factory prevents duplicate pools"
echo ""
echo "❌ Tests failing:"
echo "   → Run 'forge build' first"
echo "   → Check Solidity version compatibility"
echo "   → Ensure all dependencies installed: 'forge install'"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║            READY TO LAUNCH? YOU'VE GOT THIS! 🚀              ║"
echo "║                                                               ║"
echo "║  50+ launches = Leaderboard legend                           ║"
echo "║  Viral meme token = Community adoption                       ║"
echo "║  December 31, 2025 = Year-end awards 🏆                      ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
